# Logging

logging.level.org.springframework=info
logging.level.com.cognizant=debug

logging.level.org.hibernate.SQL=debug

# Database

spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=Ranjani@2005

# Hibernate
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true